version: '3.8'

services:
  diagnostico-app:
    image: joseojunior/diagnostico-empresarial:latest
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=1
        - traefik.http.routers.diagnostico.rule=Host(`diag.joseojunior.shop`)
        - traefik.http.routers.diagnostico.entrypoints=websecure
        - traefik.http.routers.diagnostico.tls.certresolver=letsencryptresolver
        - traefik.http.services.diagnostico.loadbalancer.server.port=80
